[package]
name = "mcl-installer"
version = "0.1.0"
authors = ["PeratX <peratx@itxtech.org>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11" }
tokio = { version = "1", features = ["full"] }
zip = "0.5"
